version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static:/app/static
    environment:
      - FLASK_ENV=production
      - BEARER_TOKEN=your token
      - DEFAULT_MODEL_ID=874c1033-932c-45c5-9357-e1fff5349557
      - DEFAULT_TEMPERATURE=0.01
      - DEFAULT_PROMPT=Old man looking at the sea

    restart: unless-stopped

